name: CheeseburgerIM - VClass
# root - port - server
root: /pyz/vclassApi/ # Server
#root: src/main/resources/static/ # Local
server:
  port: 8082 # Server: 8082 Local: 8080
  servlet:
    session:
      cookie:
        same-site: none
        secure: true
      timeout: 77m
#  address: 172.23.22.47
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.157.150.178:8081/VClass
    username: root
    password: 1029384756
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
# jodconverter:
#  local:
#    enabled: true
#    office-home: C:\Program Files (x86)\OpenOffice 4
#    max-tasks-per-process: 10
#    port-numbers: 8100
#    process-timeout: 3000000